from baremetal_benchmarking.workloads.openvino_workload import OpenvinoWorkload
from baremetal_benchmarking.workloads.redis_workload import RedisWorkload
from baremetal_benchmarking.workloads.tensorflow_workload import TensorflowWorkload
from baremetal_benchmarking.workloads.sklearnex_workload import SklearnexWorkload
from baremetal_benchmarking.workloads.memcached_workload import MemcachedWorkload
from baremetal_benchmarking.workloads.nginx_workload import NginxWorkload
from baremetal_benchmarking.workloads.specpower_workload import SpecPowerWorkload
from baremetal_benchmarking.workloads.mysql_workload import MySqlWorkload
