from baremetal_benchmarking.workloads.openvino_workload import OpenvinoWorkload
from baremetal_benchmarking.workloads.redis_workload import RedisWorkload
from baremetal_benchmarking.workloads.tensorflow_workload import TensorflowWorkload
