from docker_benchmarking.workloads.redis_workload import RedisWorkload
from docker_benchmarking.workloads.tf_serving_workload import TensorflowServingWorkload
from docker_benchmarking.workloads.inmemorydb_workload import InMemoryDBWorkload
from docker_benchmarking.workloads.pytorch_workload import PytorchWorkload